import { type NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Link from "next/link";
const DepayButton = dynamic(
  () => import("../components/Depay").then((mod) => mod.DepayButton),
  {
    ssr: false,
  }
);
const Depay: NextPage = () => {
  return (
    <>
      <Head>
        <title>NextJS Depay</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Depay test
          </h1>
          <DepayButton />
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <button></button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Depay;
